version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "gomod"
    directories:
      - "/ami-i-lazy/app"
    schedule:
      interval: "weekly"
#    reviewers:
#      - "ollypom"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directories:
      - "/ami-i-lazy"
      - "/containerized-index-builder"
    schedule:
      interval: "weekly"
#    reviewers:
#      - "ollypom"

  # Enable version updates for GitHub Actions
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#    reviewers:
#      - "ollypom"